### ISSUE TITLE
The data folder is missing

### ISSUE THREAD

**Issue by banerjeeshayantan** [KarchinLab/Tokheim_2018#1]
The folder containing all the data and notebooks, more specifically CHASMplus/data/ cannot be accessed through the link given. Is there an alternate link to access the benchamrking mutation files?

**Comment by ctokheim** [comment]
Not sure yet why the download from the lab website is not working, but you should also be able to download it from mendeley data (https://data.mendeley.com/datasets/nfkm9nb8gt/1). Hope that helps.

**Comment by banerjeeshayantan** [comment]
Thanks for the link and your prompt response. I am closing this issue.
