### ISSUE TITLE
need nucleotide mutation in test dataset.

### ISSUE THREAD

**Issue by suyufeng** [KarchinLab/Tokheim_2018#2]
For the five test datasets, you just upload the HGVSp_Short. However, My model really needs the nucleotide mutations information, which is the "Chromosome	Start_Position	End_Position	Strand	Reference_Allele	Tumor_Seq_Allele2" in the training dataset (formatted_training_list.txt). Do you have any idea to get this kind of file?

**Comment by ctokheim** [comment]
Hi. Nucleotide changes for the benchmark data are available here (https://www.dropbox.com/s/w1igwitdxu76lna/nuc_changes.tar.gz?dl=0). You'll have to merge them into the other data file that contains the scores for other methods and the protein change.

**Comment by suyufeng** [comment]
Thanks for your help! Just curious, how did you convert AA mutation to nucleotide mutation? I searched a lot but didn't find a good solution.  The main reason is most of the bed files (such as UCSC) do not match TCGA, even I selected the HG38 option. Any recommend website, workflow or tools?

**Comment by ctokheim** [comment]
The coordinates I gave you are in hg19. There multiple nucleotide substitutions that can lead to the same amino acid change. If the authors of the study I got the benchmark data from did not provide the genomic position, then I just selected one of those that lead to the same AA consequence.

**Comment by suyufeng** [comment]
I got it. Thanks.

**Comment by suyufeng** [comment]
I found the number of lines of the *_results and *.input is not match for mc3 and msk_impact.

**Comment by ctokheim** [comment]
Sorry about that. Those contained *all* mutations from MC3 and MSK IMPACT, many of which are not even missense mutations and therefore not in the benchmark. Best off fetching the info from the two MAF files for those large scale cohorts (https://www.dropbox.com/s/gtz2tjpi48pfd08/maf.tar.gz?dl=0).

**Comment by suyufeng** [comment]
So you pick all instances of which the Variant_Classification label is Missense_Mutation.

**Comment by ctokheim** [comment]
Yes, missense mutations represent the most common type of protein coding mutation in human cancers. You should be able to merge the information with the benchmarking results by matching the gene symbol and the "HGVSp_Short" column.

**Comment by suyufeng** [comment]
Awesome! Thanks for your reply!

**Comment by suyufeng** [comment]
Can you also share the maf file for the other three test datasets?  Because the nucleotide coordinates in the *.input don't match hg38 or hg37.

**Comment by ctokheim** [comment]
The other dataset never reported a MAF file. 

After double checking the nucleotide coordinates, the non-maf files are indeed in correct hg19 coordinates.  I think this is a mistake on your end.

**Comment by suyufeng** [comment]
Maybe I made a mistake, but I can't figure it out now. I found iarc_tp53 and kim_et_al are not correct. For example, the first line of iarc_tp53 is "17	7579908	7579908	T	G“ So the (17, 7579908) should be T. However, I used NCBI to search and find this site should be A (https://www.ncbi.nlm.nih.gov/nuccore/NC_000017.10?report=fasta&from=7571720&to=7590868&strand=true).
![WeChat Image_20200626210157](https://user-images.githubusercontent.com/13482814/85912255-cdbd7100-b7f0-11ea-86ea-41345a1b9d60.png)

**Comment by ctokheim** [comment]
![image](https://user-images.githubusercontent.com/2145645/85912303-8f787f80-b7f9-11ea-9ed4-caf73e69ed37.png)

**Comment by suyufeng** [comment]
Well, I find this is because ncbi used another chr17 chain. Thanks for showing the ucsc genome browser results!
