### ISSUE TITLE
List of mutations used for training not available

### ISSUE THREAD

**Issue by anaidasdfg** [KarchinLab/Tokheim_2018#3]
Hello, I am trying to download the original mutations used for training but they are not available at the provided link: [http://karchinlab.org/data/CHASMplus/formatted_training_list.txt.gz](url) 

I have checked the links provided in the closed issues and downloaded the full data folder, but I could not find this list.
Any other possibility to get the dataset?

**Comment by yang-arina** [comment]
> Hello, I am trying to download the original mutations used for training but they are not available at the provided link: [http://karchinlab.org/data/CHASMplus/formatted_training_list.txt.gz](url)
> 
> I have checked the links provided in the closed issues and downloaded the full data folder, but I could not find this list. Any other possibility to get the dataset?

Hi! Have you ever got the training set? It's also what I want!

**Comment by RachelKarchin** [comment]
https://karchinlab.org/datasets/formatted_training_llist.txt.gz

**Comment by RachelKarchin** [comment]
The links provided in this repository need to be updated. @ctokheim

**Comment by ctokheim** [comment]
Rachel, for posterity, your above link has a typo (has an extra "l") so it actually should be: https://karchinlab.org/datasets/formatted_training_list.txt.gz 

Looks like I need to fork the repo and send a pull request. So you may still need to approve it.

**Comment by ctokheim** [comment]
@RachelKarchin The link to the tarball with data relevant to running the jupyter notebooks is also broken now (http://karchinlab.org/data/CHASMplus/Tokheim_Cell_Systems_2019.tar.gz). Do you know where that is on the website now?

**Comment by RachelKarchin** [comment]
I will find it. Let's make sure everyone has the correct links. Thanks for catching the typo!

**Comment by RachelKarchin** [comment]
https://karchinlab.org/datasets/Tokheim_Cell_Systems_2019.tar.gz

**Comment by yang-arina** [comment]
I'm sorry for bother you and thank you for your patient reply again! This link does work!
